filter:
  excluded_paths:
    - 'tests/*'
    - 'vendor/*'
    - '.git/*'

build:
  timeout: 600
  environment:
    php:
      version: 8.3
      pecl_extensions:
        - redis
        - memcached
        - apcu
        - pcov
    variables:
      XDEBUG_MODE: 'off'
      PHP_COVERAGE_DRIVER: 'pcov'
      COMPOSER_PROCESS_TIMEOUT: 600
  dependencies:
    override:
      - composer self-update --no-interaction
      - composer install --no-interaction --prefer-dist --ansi
  tools:
    php_code_sniffer:
      enabled: true
      config:
        standard: PSR12
    phpstan:
      enabled: true
      version: '1.12.*'
      config_file: phpstan.neon
      level: 9
  tests:
    override:
      - command: >
          ./vendor/bin/phpunit
          --configuration phpunit.xml.dist
          --coverage-clover coverage/clover.xml
          --colors=never
        coverage:
          file: coverage/clover.xml
          format: php-clover
